module.exports = [
  'Abimegender',
  'Adamasgender',
  'Aerogender',
  'Aesthetigender',
  'Affectugender',
  'Agender',
  'Agenderflux',
  'Alexigender',
  'Aliusgender',
  'Amaregender',
  'Ambigender',
  'Ambonec',
  'Amicagender',
  'Androgyne',
  'Androgynous',
  'Anesigender',
  'Angenital',
  'Anogender',
  'Anongender',
  'Antegender',
  'Anxiegender',
  'Apagender',
  'Apconsugender',
  'Astergender',
  'Astralgender',
  'Autogender',
  'Axigender',
  'Bigender',
  'Biogender',
  'Blurgender',
  'Boyflux',
  'Burstgender',
  'Caelgender',
  'Cassgender',
  'Cassflux',
  'Cavusgender',
  'Cendgender',
  'Ceterofluid',
  'Ceterogender',
  'Cis',
  'Cisgender',
  'Cis Female',
  'Cis Male',
  'Cis Man',
  'Cis Woman',
  'Cisgender Female',
  'Cisgender Male',
  'Cisgender Man',
  'Cisgender Woman',
  'Cloudgender',
  'Collgender',
  'Colorgender',
  'Commogender',
  'Condigender',
  'Deliciagender',
  'Demifluid',
  'Demiflux',
  'Demigender',
  'Domgender',
  'Duragender',
  'Egogender',
  'Epicene',
  'Espigender',
  'Exgender',
  'Existigender',
  'Female to Male',
  'Femfluid',
  'Femgender',
  'Fluidflux',
  'FTM',
  'Gemigender',
  'Genderblank',
  'Genderflow',
  'Genderfluid',
  'Genderflux',
  'Genderfuzz',
  'Gender Neutral',
  'Gender Nonconforming',
  'Genderpunk',
  'Genderqueer',
  'Gender Questioning',
  'Gender Variant',
  'Genderwitched',
  'Girlflux',
  'Glassgender',
  'Glimragender',
  'Greygender',
  'Gyragender',
  'Healgender',
  'Heliogender',
  'Hemigender',
  'Horogender',
  'Hydrogender',
  'Imperigender',
  'Intergender',
  'Juxera',
  'Libragender',
  'Magigender',
  'Male to Female',
  'Mascfluid',
  'Mascgender',
  'Maverique',
  'Mirrorgender',
  'Molligender',
  'Multigender',
  'MTF',
  'Nanogender',
  'Neither',
  'Neutrois',
  'Non-binary',
  'Omnigender',
  'Oneirogender',
  'Other',
  'Pangender',
  'Paragender',
  'Perigender',
  'Polygender',
  'Proxvir',
  'Quoigender',
  'Subgender',
  'Surgender',
  'Systemgender',
  'Tragender',
  'Trans',
  'Trans*',
  'Trans Female',
  'Trans* Female',
  'Trans Male',
  'Trans* Male',
  'Trans Man',
  'Trans* Man',
  'Trans Person',
  'Trans* Person',
  'Trans Woman',
  'Trans* Woman',
  'Transfeminine',
  'Transgender',
  'Transgender Female',
  'Transgender Male',
  'Transgender Man',
  'Transgender Person',
  'Transgender Woman',
  'Transmasculine',
  'Transsexual',
  'Transsexual Female',
  'Transsexual Male',
  'Transsexual Man',
  'Transsexual Person',
  'Transsexual Woman',
  'Trigender',
  'Two-Spirit',
  'Vapogender',
  'Venngender',
  'Verangender',
  'Vibragender',
  'Vocigender'
]
